package provider

import (
	"context"
	"github.com/elasticpath/terraform-provider-epcc/external/sdk/epcc"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceEpccPromotion() *schema.Resource {
	return &schema.Resource{
		Description: `Represents the EPCC API [Promotion Object](https://documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html#the-promotion-object).
!> **Warning:** This resource only supports a single schema at this point
`,

		CreateContext: addDiagToContext(resourceEpccPromotionCreate),
		ReadContext:   addDiagToContext(resourceEpccPromotionRead),
		UpdateContext: addDiagToContext(resourceEpccPromotionUpdate),
		DeleteContext: addDiagToContext(resourceEpccPromotionDelete),
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{
			"id":             {Type: schema.TypeString, Computed: true},
			"name":           {Type: schema.TypeString, Required: true, Description: "Specifies a name for the promotion."},
			"description":    {Type: schema.TypeString, Required: true, Description: "Specifies a description for the promotion."},
			"enabled":        {Type: schema.TypeBool, Required: true, Description: "Specifies whether the promotion is enabled. The options are `true` or `false`, and the default setting is `false`."},
			"automatic":      {Type: schema.TypeBool, Optional: true, Description: "Specifies whether the promotion is applied automatically to the cart or a code is required to apply the promotion. The default setting is `false`. When this value is set `true`, a code is autogenerated. If this value is set `false`, you must create the code manually"},
			"promotion_type": {Type: schema.TypeString, Required: true, Description: "Specifies the type of the promotion."},
			"schema": {Type: schema.TypeList, Required: true,
				Elem: &schema.Resource{Schema: map[string]*schema.Schema{
					"currencies": {Type: schema.TypeList, Optional: true,
						Elem: &schema.Resource{Schema: map[string]*schema.Schema{
							"currency": {Type: schema.TypeString, Optional: true},
							"amount":   {Type: schema.TypeInt, Optional: true},
						}}},
				}}},
			"start": {Type: schema.TypeString, Required: true, Description: "Specifies the start date and time of the promotion or the start date of the promotion. You can provide a specific time in the HH:MM format. For example, `\"start\": \"2000-01-01 12:00\"`."},
			"end":   {Type: schema.TypeString, Required: true, Description: "Specifies the end date and time of the promotion or the end date of the promotion."},
			"min_cart_value": {Type: schema.TypeList, Optional: true, Description: "Provide the minimum cart value required for the promotion to apply",
				Elem: &schema.Resource{Schema: map[string]*schema.Schema{
					"currency": {Type: schema.TypeString, Optional: true},
					"amount":   {Type: schema.TypeInt, Optional: true},
				}}},
			"max_discount_value": {Type: schema.TypeList, Optional: true, Description: "provides the maximum possible discount for the cart",
				Elem: &schema.Resource{Schema: map[string]*schema.Schema{
					"currency": {Type: schema.TypeString, Optional: true},
					"amount":   {Type: schema.TypeInt, Optional: true},
				}}},
		},
	}

}

func resourceEpccPromotionDelete(ctx context.Context, d *schema.ResourceData, m interface{}) {
	client := m.(*epcc.Client)
	promotionID := d.Id()

	err := epcc.Promotions.Delete(&ctx, client, promotionID)

	if err != nil {
		ReportAPIError(ctx, err)
	}

	d.SetId("")
}

func resourceEpccPromotionUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) {
	client := m.(*epcc.Client)

	promotionId := d.Id()
	schemas := d.Get("schema").([]interface{})
	singleSchema := schemas[0]
	promotion := &epcc.Promotion{
		Id:               promotionId,
		Type:             "promotion",
		Name:             d.Get("name").(string),
		Description:      d.Get("description").(string),
		Enabled:          d.Get("enabled").(bool),
		Automatic:        d.Get("automatic").(bool),
		PromotionType:    d.Get("promotion_type").(string),
		Start:            d.Get("start").(string),
		End:              d.Get("end").(string),
		Schema:           singleSchema,
		MinCartValue:     d.Get("min_cart_value").(interface{}),
		MaxDiscountValue: d.Get("max_discount_value").(interface{}),
	}

	updatedPromotionData, apiError := epcc.Promotions.Update(&ctx, client, promotionId, promotion)

	if apiError != nil {
		ReportAPIError(ctx, apiError)
		return
	}

	d.SetId(updatedPromotionData.Data.Id)

	resourceEpccPromotionRead(ctx, d, m)
}

func resourceEpccPromotionRead(ctx context.Context, d *schema.ResourceData, m interface{}) {
	client := m.(*epcc.Client)

	promotionId := d.Id()

	promotion, err := epcc.Promotions.Get(&ctx, client, promotionId)

	if err != nil {
		ReportAPIError(ctx, err)
		return
	}

	if err := d.Set("name", promotion.Data.Name); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
	if err := d.Set("description", promotion.Data.Description); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
	if err := d.Set("enabled", promotion.Data.Enabled); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
	if err := d.Set("automatic", promotion.Data.Automatic); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
	if err := d.Set("promotion_type", promotion.Data.PromotionType); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
	if err := d.Set("start", promotion.Data.Start); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
	if err := d.Set("end", promotion.Data.End); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}

	singleSchema := promotion.Data.Schema.(map[string]interface{})

	currencySingleSchema := make(map[string]interface{})
	currencySingleSchema["currencies"] = singleSchema["currencies"]

	if err := d.Set("schema", [1]interface{}{currencySingleSchema}); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
	if err := d.Set("min_cart_value", promotion.Data.MinCartValue); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
	if err := d.Set("max_discount_value", promotion.Data.MaxDiscountValue); err != nil {
		addToDiag(ctx, diag.FromErr(err))
		return
	}
}

func resourceEpccPromotionCreate(ctx context.Context, d *schema.ResourceData, m interface{}) {
	client := m.(*epcc.Client)
	schemas := d.Get("schema").([]interface{})
	singleSchema := schemas[0]
	promotion := &epcc.Promotion{
		Type:             "promotion",
		Name:             d.Get("name").(string),
		Description:      d.Get("description").(string),
		Enabled:          d.Get("enabled").(bool),
		Automatic:        d.Get("automatic").(bool),
		PromotionType:    d.Get("promotion_type").(string),
		Schema:           singleSchema,
		Start:            d.Get("start").(string),
		End:              d.Get("end").(string),
		MinCartValue:     d.Get("min_cart_value").(interface{}),
		MaxDiscountValue: d.Get("max_discount_value").(interface{}),
	}
	createdPromotionData, apiError := epcc.Promotions.Create(&ctx, client, promotion)
	if apiError != nil {
		ReportAPIError(ctx, apiError)
		return
	}

	d.SetId(createdPromotionData.Data.Id)

	resourceEpccPromotionRead(ctx, d, m)
}
