package epcc_docs

var DOCS_CSV=`
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','id','string','The unique identifier for this file.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','type','string','The type represents the object being returned.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','The file ','link object','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','file_name','string','The name of the file.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','mime_type','string','The mime type of the file.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','file_size','integer','The size of the file. Required when uploading files.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','public','boolean','Whether the file public or not. Required when uploading files.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','file_location','string','The URL that points to an image. Required when referencing files stored externally.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','The additional ','meta object','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','The file ','links object','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','link.href','string','The publicly available URL for this file.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','meta.dimensions.width','integer','The width of the file.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','meta.dimensions.height','integer','The height of the file.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','meta.timestamps.created_at','string','The creation date of the file.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','links.self','string','The URL of this file object.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html',' / ','like','eq(file_name, my_image.jpg)'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html',' / ','le','gt(with,200)'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html',' / ','le','lt(height,500)'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html','boolean','eq','eq(public,true)'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/files/index.html',' / ','le','le(file_size,20953)'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html','Required','string','The Bearer token required to get access to the API.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html','Required','object','The webhook configuration object.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html','Required','array','An array of events you want to observe.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html','Should the event trigger or not. Default:','false','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html','Required','string','webhook'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html','Required','string','A description for the event.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html','Required','string','The name of the event.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html','Required','string','Represents the type of object.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/create-an-event.html',' header. Useful to authenticate the response came from Elastic Path. This is sent as ','X-MOLTIN-SECRET-KEY','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/index.html','id','string','The unique identifier for the event.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/index.html','type','string','This represents the type of object being returned.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/index.html','name','string','The name of the event.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/index.html','description','string','A description for this event.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/index.html','string','This is ','webhook'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/index.html','enabled','boolean','This enables the event to fire.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/index.html','An array of ','observable events','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/events/index.html',' ','configuration object','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','id','string','The unique identifier for this currency.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','type','string','The type represents the object being returned.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','code','string','The currency code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','exchange_rate','float','The exchange rate.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','How to structure a currency; e.g., ','&quot;${price}&quot;','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','decimal_point','string','The decimal point character.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','thousand_separator','string','The thousand separator character.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','decimal_places','integer','The amount of decimal places the currency is formatted to.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html',' (default: ','false',').'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','links','object','The links object.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','meta','object','The meta object.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','links.self','string','The URL of this currency.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','meta.timestamps','object','Timestamps for this currency.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','meta.timestamps.created_at','string','The creation date of this currency.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/currencies/index.html','meta.timestamps.updated_at','string','The updated date of this currency.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/flows/index.html','id','string','The unique identifier for this flow.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/flows/index.html','type','string','Represents the type of object being returned.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/flows/index.html','name','string','The name of the flow.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/flows/index.html','slug','string','A unique slug identifier for the flow.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/flows/index.html','description','string','Any description for this flow.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/flows/index.html',' if enabled, ','false',' if not.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','id','string','The unique identifier for this field.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','Represents the type of object being returned.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','name','string','The name of the field.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','slug','string','A unique slug identifier for the field.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html',', or ','relationship','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','See ','Field Validation Rules','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','description','string','Any description for this field.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html',' if the ','field_type',' is a relationship.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','default','mixed','A default value if none is supplied and field is not required.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html',', otherwise ','false','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','order','integer','Denotes the order in which this field is returned relative to the rest of the flow fields.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','relationships','object','A relationship object to link this field to a flow.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','Hide this field from responses if the value is ','null','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','enum'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','options','array[string]','An array of valid string values.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','email'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','slug'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','enum'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html',' and ','to',' integers.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','enum'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','options','array[integer]','An array of valid integer values.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','enum'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html',' and ','to',' floats.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','enum'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','options','array[float]','An array of valid float values.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','enum'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','An array of valid date values as strings (','YYYY-MM-DD HH:MM:SS',' - time is optional).'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','one-to-many'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','The entity type you are making relationships with in singular form (e.g., ','product',').'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','type','string','one-to-one'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/fields/index.html','The entity type you are making relationships with in singular form (e.g., ','customer',').'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/orders-and-customers/customers/index.html','id','string','The unique identifier for this customer.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/orders-and-customers/customers/index.html','type','string','The type represents the object being returned.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/orders-and-customers/customers/index.html','The ','name',' of the customer.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/orders-and-customers/customers/index.html','The ','email',' of the customer.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/orders-and-customers/customers/index.html',' if the customer has a password, ','false',' otherwise.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/orders-and-customers/customers/index.html','string','eq','eq(email,ronswanson@example.com)'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','id','string','The unique identifier for an Account.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','type','string','The type of the object returned..'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','name','string','The name of the account.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','legal_name','string','The legal name of the account.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','registration_id','string','The registration ID of the account.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','Additional information for this realm. For more information, see ','The meta object',' section.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','A list of related resources. For more information, see ','The relationships object',' section.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','meta.timestamps','string','Specifies the time and date that the account is created or updated.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','meta.timestamps.created_at','string','Specifies the date the account is created.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','meta.timestamps.updated_at','string','Specifies the date the account is last updated.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','relationships.parent','object','Provides details about the relationship between the account and the parent account.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','relationships.parent.data','object','Specifies the details of the parent account.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','relationships.parent.data.id','string','Specifies the id of the parent account.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','relationships.parent.data.type','string','Specifies the type of the parent account.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','relationships.ancestors','object','Displays an array with the details about the relationship between an account and the ancestors of the account. The first index of the array is the top-level account and the last index is the parent of this account. This field is displayed only if the account has ancestors.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','relationships.ancestors[x].data','object','Specifies the information regarding a specific ancestor.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','relationships.ancestors[x].data.id','string','Specifies the ID of the ancestor.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/account-management/accounts/index.html','relationships.ancestors[x].data.type','string','Specifies the type of the ancestor.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','id','string','The unique identifier of the price book.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','string','Always: ','pricebook'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','attributes.name','string','The name of the price book.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','attributes.description','string','The purpose for the price book, such as flash sale pricing or preferred customer pricing.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','attributes.created_at','string($date-time)','Generated value. The date and time when the price book was created.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','attributes.updated_at','string($date-time)','Generated value. The date and time when the price book was last updated.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','data','array','Displays details about the price book, excluding products and prices.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','links','object','Links among the price books in the list.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','id','string','The generated unique identifier of the product price resource. The product price ID is not the same as the ID of the product.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','string','Always: ','product-price'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','attributes.sku','string','The product SKU that the prices belongs to.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','A collection of one or more ','currencies: &lt;key&gt;',' objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','Where ','&lt;key&gt;',' is the three-letter ISO code for the currency associated with this price.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','currencies: &lt;key&gt;: amount','integer','The price in the lowest denomination for the specified currency.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','Whether this price includes tax. Default is ','false','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/pricebooks/index.html','id','string','The unique identifier of a product.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','string','Always: ','hierarchy'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','id','string','The generated unique identifier for the hierarchy.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','The name of the hierarchy, such as ','Major Appliances','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','attributes.description','string','A description of the hierarchy.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','attributes.slug','string','A unique slug for the hierarchy.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','string','Always: ','node'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','id','string','The generated unique identifier for the node.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html',' or ','Refrigerators','. Names must be unique among sibling nodes in the hierarchy. Otherwise, a name can be non-unique within the hierarchy and across multiple hierarchies.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','attributes.description','string','A description of the node.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/pcm/hierarchies/index.html','attributes.slug','string','A slug for the node. Slugs must be unique among sibling nodes in the hierarchy. Otherwise, a slug can be non-unique within the hierarchy and across multiple hierarchies.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','type','string','promotion'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','name','string','The name of a promotion.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','description','string','The description of a promotion.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','enabled','boolean','Indicates whether a promotion is active.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','automatic','boolean','Allows promotion to be applied without the need for a code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','item_fixed_discount',', or ','item_percent_discount'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html',', or ','Item Percent Discount','.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','min_cart_value','array','array of objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','min_cart_value[].currency','string','A currency code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','min_cart_value[].amount','integer','The minimum cart value before promotion is applied.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','max_discount_value','array','array of objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','max_discount_value[].currency','string','A currency code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','max_discount_value[].amount','integer','The maximum value of the discount.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','start','string','The start time of the promotion DateTime.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','end','string','The end time of the promotion DateTime.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies','array','An array of objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].currency','string','A currency code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].amount','integer','The amount to discount by.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies','array','An array of objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].currency','string','A currency code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].percentage','float','The percentage to discount by.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','x','integer','Number of items required to activate promotion.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','y','integer','Number of items that are used to calculate the total charge.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','targets','array','Array of strings.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','targets[]','string','A list of strings that represent the productIDs and/or SKUs.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','x','integer','Number of items required to activate promotion.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies','array','Array of objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].currency','string','A currency code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].amount','integer','The amount to vend items for.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','requirements','array','Array of objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','requirements[].targets','array','Array of strings.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','requirements[].targets[]','string','A list of strings that represent the productIDs and/or SKUs.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','requirements[].quantity','integer','The require number of corresponding target to satisfy the promotion.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies','array','Array of objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].currency','string','A currency code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].amount','integer','The amount to vend items for.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies','array','Array of objects.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].currency','string','A currency code.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','currencies[].amount','integer','An amount to vend items for.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','targets','array','Array of strings.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','targets[]','string','A list of strings that represent the productIDs or SKUs.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','percent','number','The percentage to discount.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','code','string','Any string.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','uses','integer','Limit for number of times this code can be used.'
'./build/documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/promotions/index.html','user','string','A string used as an identifier relating to a user.'
`
